version: "3.9"   

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hangergame
      - POSTGRES_USER=hangergame
      - POSTGRES_PASSWORD=hangergame
    container_name: hangergamedb1
  
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8002:8000"
    environment:
      - POSTGRES_NAME=hangergame
      - POSTGRES_USER=hangergame
      - POSTGRES_PASSWORD=hangergame
    restart: always
    image: hangergameimage
    volumes:
      - .:/hanger/container
    container_name: hangergameweb1
    depends_on:
      - db
  
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=omar.hesham.alex2016@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 82:80
    restart: always
    container_name: hangergamepgadmin1