# Generated by Django 4.1.1 on 2022-09-22 07:09

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('Last_update_date', models.DateTimeField(auto_now=True)),
                ('Last_update_by', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('party_number', models.CharField(max_length=200)),
                ('party_name', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=400)),
                ('party_type', models.CharField(choices=[(1, 'Customer'), (2, 'Supplier')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
