# Generated by Django 4.1.1 on 2022-10-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Party', '0002_alter_parties_party_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='party_type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Supplier')]),
        ),
    ]
