# Generated by Django 4.1.1 on 2022-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
