# Generated by Django 4.1.1 on 2022-09-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_navbar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='order_by',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
