# Generated by Django 4.1.1 on 2022-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_navbar_order_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='child_list_flag',
            field=models.BooleanField(default=True),
        ),
    ]
