# Generated by Django 4.1.1 on 2022-09-27 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_projectapp_alter_navbar_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='app_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.projectapp'),
        ),
    ]
