# Generated by Django 4.1.1 on 2022-09-22 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_remove_invoicelines_item_remove_orderlines_item_and_more'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='order_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales.orderheaders'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales.orderlines'),
        ),
        migrations.AddField(
            model_name='transactionstemp',
            name='order_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales.orderheaders'),
        ),
        migrations.AddField(
            model_name='transactionstemp',
            name='order_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales.orderlines'),
        ),
    ]
