# Generated by Django 4.1.1 on 2022-09-22 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0002_remove_purchaselines_item'),
        ('Inventory', '0002_transactions_order_header_transactions_order_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='purchase_Line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Purchasing.purchaselines'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='purchase_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Purchasing.purchaseheaders'),
        ),
        migrations.AddField(
            model_name='transactionstemp',
            name='purchase_Line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Purchasing.purchaselines'),
        ),
        migrations.AddField(
            model_name='transactionstemp',
            name='purchase_header',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Purchasing.purchaseheaders'),
        ),
    ]
