# Generated by Django 4.1.1 on 2022-10-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_transactions_purchase_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='batch_flag',
            field=models.BooleanField(max_length=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='complete_flag',
            field=models.BooleanField(max_length=1),
        ),
        migrations.AlterField(
            model_name='items',
            name='order_flag',
            field=models.BooleanField(max_length=1),
        ),
    ]
