# Generated by Django 4.1.1 on 2022-09-22 07:15

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Party', '0001_initial'),
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('Last_update_date', models.DateTimeField(auto_now=True)),
                ('Last_update_by', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('po_number', models.IntegerField()),
                ('status', models.CharField(choices=[(1, 'Entered'), (2, 'Approve'), (3, 'Canceled'), (4, 'Close')], max_length=1)),
                ('total_purchase', models.ImageField(upload_to='')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Party.parties')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('Last_update_date', models.DateTimeField(auto_now=True)),
                ('Last_update_by', models.IntegerField(verbose_name=django.contrib.auth.models.User)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('status', models.CharField(choices=[(1, 'Entered'), (2, 'Approve'), (3, 'Canceled'), (4, 'Close')], max_length=1)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchasing.purchaseheaders')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.items')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
