# Generated by Django 4.1.1 on 2022-09-22 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchasing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselines',
            name='item',
        ),
    ]
