# Generated by Django 4.1.1 on 2022-09-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_transactions_purchase_line_and_more'),
        ('Purchasing', '0002_remove_purchaselines_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselines',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.items'),
        ),
    ]
