# Generated by Django 4.1.1 on 2022-09-22 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelines',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderlines',
            name='item',
        ),
        migrations.RemoveField(
            model_name='pricelistlines',
            name='item',
        ),
    ]
