# Generated by Django 4.1.1 on 2022-09-22 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_transactions_purchase_line_and_more'),
        ('Sales', '0002_remove_invoicelines_item_remove_orderlines_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelines',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.items'),
        ),
        migrations.AddField(
            model_name='orderlines',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.items'),
        ),
        migrations.AddField(
            model_name='pricelistlines',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.items'),
        ),
    ]
