# Generated by Django 4.1.1 on 2022-10-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_alter_invoiceheaders_last_update_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheaders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Entered'), (2, 'Booked'), (3, 'Canceled'), (4, 'Complete')], max_length=1),
        ),
        migrations.AlterField(
            model_name='orderlines',
            name='status',
            field=models.IntegerField(choices=[(1, 'Entered'), (2, 'Booked'), (3, 'Canceled'), (4, 'Complete')], max_length=1),
        ),
        migrations.AlterField(
            model_name='orderlines',
            name='wasted_flag',
            field=models.BooleanField(),
        ),
    ]
