# Generated by Django 4.1.1 on 2022-10-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_orderheaders_status_alter_orderlines_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheaders',
            name='discount_type',
            field=models.IntegerField(choices=[(1, 'percentage'), (2, 'Amount')]),
        ),
        migrations.AlterField(
            model_name='invoicelines',
            name='discount_type',
            field=models.IntegerField(choices=[(1, 'percentage'), (2, 'Amount')]),
        ),
        migrations.AlterField(
            model_name='orderheaders',
            name='discount_type',
            field=models.IntegerField(choices=[(1, 'percentage'), (2, 'Amount')]),
        ),
        migrations.AlterField(
            model_name='orderheaders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Entered'), (2, 'Booked'), (3, 'Canceled'), (4, 'Complete')]),
        ),
        migrations.AlterField(
            model_name='orderlines',
            name='discount_type',
            field=models.IntegerField(choices=[(1, 'percentage'), (2, 'Amount')]),
        ),
        migrations.AlterField(
            model_name='orderlines',
            name='status',
            field=models.IntegerField(choices=[(1, 'Entered'), (2, 'Booked'), (3, 'Canceled'), (4, 'Complete')]),
        ),
    ]
