# Generated by Django 4.1.1 on 2022-10-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_alter_invoiceheaders_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceheaders',
            name='total_order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderheaders',
            name='total_order',
            field=models.IntegerField(),
        ),
    ]
