# Generated by Django 4.1.1 on 2022-10-12 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_alter_invoiceheaders_total_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistlines',
            name='header',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Sales.pricelistheaders'),
            preserve_default=False,
        ),
    ]
